language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 

before_install:
 - wget "https://download.mono-project.com/archive/4.6.1/macos-10-universal/MonoFramework-MDK-4.6.1.5.macos10.xamarin.universal.pkg"
 - sudo installer -pkg "MonoFramework-MDK-4.6.1.5.macos10.xamarin.universal.pkg" -target /
 
script:
 - make test

